# Generated by Django 4.0.3 on 2022-03-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.IntegerField()),
                ('Student_fname', models.CharField(max_length=200)),
                ('Student_lname', models.CharField(max_length=100)),
                ('Birth_Date', models.DateField(auto_now_add=True)),
                ('Gender', models.CharField(max_length=50)),
            ],
        ),
    ]
