# Generated by Django 4.0.2 on 2022-03-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_student_birth_date_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Other_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Address', models.CharField(max_length=200)),
                ('Student_Email', models.EmailField(max_length=254)),
                ('Student_Phone', models.IntegerField()),
                ('Student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.student')),
            ],
        ),
    ]
