# Generated by Django 4.0.2 on 2022-03-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_student_other_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Other_info',
        ),
    ]
